name: Pull Request

on:
  pull_request:

jobs:
  static_analysis:
    uses: mindee/mindee-api-java/.github/workflows/_static-analysis.yml@main
  build:
    uses: mindee/mindee-api-java/.github/workflows/_build.yml@main
    needs: static_analysis
    secrets: inherit
  codeql:
    uses: mindee/mindee-api-java/.github/workflows/_codeql.yml@main
    needs: build
  test_integrations:
    uses: mindee/mindee-api-java/.github/workflows/_test-integrations.yml@main
    needs: build
    secrets: inherit
  test_code_samples:
    uses: mindee/mindee-api-java/.github/workflows/_test-code-samples.yml@main
    needs: build
    secrets: inherit
